### PR TITLE
chore: Format landing page file

### PR DESCRIPTION
**Pull request by dnys1**
Runs prettier on `LandingPage.tsx`

### CODE REVIEW

**Comment by dnys1** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/celest-dev/website/50?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #47** <a href="https://app.graphite.dev/github/pr/celest-dev/website/47?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #48** <a href="https://app.graphite.dev/github/pr/celest-dev/website/48?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #49** <a href="https://app.graphite.dev/github/pr/celest-dev/website/49?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #50** <a href="https://app.graphite.dev/github/pr/celest-dev/website/50?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/celest-dev/website/50?utm_source=stack-comment).

**Comment by dnys1** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/celest-dev/website/50?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #47** <a href="https://app.graphite.dev/github/pr/celest-dev/website/47?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #48** <a href="https://app.graphite.dev/github/pr/celest-dev/website/48?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #49** <a href="https://app.graphite.dev/github/pr/celest-dev/website/49?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #50** <a href="https://app.graphite.dev/github/pr/celest-dev/website/50?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/celest-dev/website/50?utm_source=stack-comment).

**Review by abdallahshaban557 — APPROVED** [review]
LGTM

**Comment by dnys1** [comment]
### Merge activity

* **Jan 16, 12:51 PM**: @dnys1 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/celest-dev/website/50).

**Pull request merged**
